### PR TITLE
Testing the methods 

### PR DESCRIPTION
**Pull request by Oghenebrume50**

### CODE REVIEW

**Comment by dipto0321** [comment]
HI, @Oghenebrume50  and @shloch ,

Good job !. All tests are passing. You write test important functions as you think. For this project, this is from me 👍 . But keep practicing, because in the future when you are going to do `TDD (Test Driven Development)` before building rails project which will be really a good habit if you can build it. You have to do a lot of things for writing a better spec. Here is a guide for [betterspec](http://www.betterspecs.org/).

I have a question. Why there is only @Oghenebrume50 commits for testing? What about @shloch ?

Thanks ☺️

**Comment by Oghenebrume50** [comment]
@dipto0321 thanks for the review we would definitely take testing more serious, @shloch wrote a better part of the Tic-tac-toe project himself because I was sick then, this is my way of contributing immersely to the whole project, we worked through it together though.

**Comment by shloch** [comment]
> betterspec

Thanks @dipto0321 , i was doing Rubocop error fixing for same project on another branch (MASTER), while my coding partner was doing RSPEC testing on testing branch, Upon merge...... you will notice substantial participation from both of us

**Comment by dipto0321** [comment]
@Oghenebrume50 and @shloch ,

Got it. Thanks for sharing ☺️ 👍 👍

**Pull request merged**
